### ISSUE TITLE
[依頼]Chatspace挙動確認

### ISSUE THREAD

**Issue by takanori-k-1074** [takanori-k-1074/chat-space#11]
＃IPアドレス
54.248.135.191

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by takanori-k-1074** [comment]
ご指導ありがとうございました
